### ISSUE TITLE
Better handling of SSL errors

### ISSUE THREAD

**Issue by bubbob42** [sacredbanana/AmigaGPT#10]
AmigaGPT currently does not like SSL errors.

To reproduce:

- set system time to a wrong date, e.g. two years back
- request image generation
- AmigaGPT will show SSL_ERROR_SSL and SSL_ERROR_SYSCALL
- click any "show image button". 
- > error: Could not create dataTypeObject 

The display routine may have to check whether the image really exists.

**Comment by sacredbanana** [comment]
This is now fixed in the 1.4.3 release! Thanks for the report!
