### ISSUE TITLE
Program warns about too small stack size (8192) if starting from Workbench

### ISSUE THREAD

**Issue by gustavosarmento** [sacredbanana/AmigaGPT#12]
Title says it all, basically.

AmigaGPT 1.4.3
Kickstart 47.111
Workbench 47.4
narrator.device v34 and v37 on correct places
translator.library 43.1
Amiga 1200/TF1260/128 MB Fast RAM

**Comment by sacredbanana** [comment]
Sorry about that, I didn't set the stack size in AmigaGPT's .info file to the recommended 32768 bytes. I will fix that in the next version. In the meantime, you can easily fix this by selecting AmigaGPT's icon, then in the right click menu, go to the `Icons` menu then select `Information`. In the information panel select the `Icon` tab then set the stack to 32768 bytes. When you hit save it will use this new stack size from now on.

<img width="337" alt="image" src="https://github.com/sacredbanana/AmigaGPT/assets/6903516/f62afc95-fdc7-44d1-850c-9c0f3e075a4b">

**Comment by gustavosarmento** [comment]
Tried your solution, but unfortunately the error message persists.

**Comment by sacredbanana** [comment]
If you go back to the information panel again, does it still show 32768?

Does the warning message always report your stack to be 8192 bytes?

Another thing you can try is in your Prefs folder, open Workbench prefs and set stack size in there to 32kb

**Comment by gustavosarmento** [comment]
Yes, 32768 if coming back to the Information panel.

The warning message always reports that my stack is 8192 bytes (only once it reported 8448 bytes, but I couldn't reproduce it since), and my Workbench Prefs was originally set to a 4 KB stack (this being the default, I assume). Setting it to 32 KB or more doesn't change the error.

**Comment by sacredbanana** [comment]
what about if you execute it via the Shell before typing in the command `STACK 32768`?

**Comment by gustavosarmento** [comment]
...then it runs with no warnings.

**Comment by sacredbanana** [comment]
Ok odd. For some reason your workbench is both ignoring the icon stack size and also the internal stack cookie. Have you updated your AmigaOS with the 2 update files to AmigaOS 3.2.2?

**Comment by gustavosarmento** [comment]
Yep, I'm on Workbench 3.2.2.1. And I don't use any third-party "performance patches" or "eye candy", trying to avoid such strange compatibility issues.

**Comment by sacredbanana** [comment]
Try the new 1.4.4 release and let me know if it still happens

**Comment by gustavosarmento** [comment]
Forgot to mention on my last reply that I was already on 1.4.4.

Unfortunately, the issue persists. I'm starting to wonder if it isn't something on my setup, as clean as it may seem...

**Comment by sacredbanana** [comment]
it weird because it works fine for me (on my MiSTer and in AmiKit)

**Comment by gustavosarmento** [comment]
Apparently, PeterK on EAB Board found the issue. Says him:

"AmigaGPT seems indeed to have a bug. When reading the stack size from its tool icon it divides the size by 4 by mistake! So, for an entry of 32768 it just sees 8192 bytes of stack.

When I tried 140000 for the stack setting AmigaGPT didn't complain anymore, but 131072 should also work (not tested)."

**Comment by gustavosarmento** [comment]
Just tested here, and indeed: 131072 of stack size gives no warning. Reducing to 130048 already warns that "a stack size of 32512 bytes is too small".

**Comment by sacredbanana** [comment]
I added a print statement to read out the stack size. When launching from the tool icon (which is set to 32768) it does indeed have 32768 bytes in stack and also does not show the warning for me. Also tested setting custom stack in CLI when launching from the shell.

<img width="489" alt="image" src="https://github.com/sacredbanana/AmigaGPT/assets/6903516/fb071fd4-abc6-4ca3-82df-888b5166a87e">

**Comment by gustavosarmento** [comment]
Can I reproduce these steps here on my system?

**Comment by gustavosarmento** [comment]
Turns out, PeterK went onto great lengths to find that, indeed, the bug is on AmigaGPT's code. Two posts worth noting:

https://eab.abime.net/showpost.php?p=1676793&postcount=13

https://eab.abime.net/showpost.php?p=1676804&postcount=14

**Comment by sacredbanana** [comment]
Thanks for your assistance with this issue. I have now fixed it in version 1.4.5
