### ISSUE TITLE
translator.library error window when generating a response

### ISSUE THREAD

**Issue by gustavosarmento** [sacredbanana/AmigaGPT#13]
When AmigaGPT starts to generate a response, translator.library opens an "object not found" error window.

AmigaGPT 1.4.3
Kickstart 47.111
Workbench 47.4
narrator.device v34 and v37 on correct places
translator.library 43.1
Amiga 1200/TF1260/128 MB Fast RAM

**Comment by sacredbanana** [comment]
When you ran the installer for translator.library, did you let it install all the accent files? Also try changing the accent in the Speech menu in AmigaGPT and see if changing the accent helps.

**Comment by gustavosarmento** [comment]
Yes, all accent files installed. Choosing another accent doesn't change the erroneous behavior, unfortunately.

**Comment by gustavosarmento** [comment]
AmigaOS 3.2.2 (Kickstart 47.111, Workbench 47.4).

**Comment by sacredbanana** [comment]
Long shot, have you tried deleting translator entirely and reinstalling and repatching?

**Comment by gustavosarmento** [comment]
I did it, and nothing changed.

But I managed to get SnoopDOS running, and it only got weirder: SnoopDOS accused an error trying to load LOCALE:Accents/.accent. So I made a copy of american.accent, renamed it to .accent, and put it there.
For the next first response, it worked! But for all subsequent ones, now it asks for a volume named after the first n words of the answer!

Deleting the .accent file, this behavior remains!

I know, bonkers.

**Comment by sacredbanana** [comment]
have a look at your config.json file. there should be an entry for accent in there. maybe there's a bug where its not saving correctly in there. can you check that for me?

**Comment by gustavosarmento** [comment]
"speechAccent":"Ita",

Never chose Italian! And should it be abbreviated? What do I change it to?

**Comment by sacredbanana** [comment]
just change it to the full name of what the accent file is you want to use. Sorry this is a bug in the config saving it seems so I'll look into it for the next version. Thanks a lot

**Comment by gustavosarmento** [comment]
Changing it to the full name on the config.json file had no effect. I even reinstalled AmigaGPT from scratch and the issue persists.

**Comment by sacredbanana** [comment]
Yes I discovered a bug in the loading of accents. Turns out I completely broke it. I just fixed it and it will be in the next release

**Comment by sacredbanana** [comment]
New version with the fix released. Get version 1.4.4 and you won't have this issue anymore. Thanks for the bug report!

**Comment by gustavosarmento** [comment]
Issue fixed indeed! Thanks!
