### ISSUE TITLE
offline mode

### ISSUE THREAD

**Issue by vastago** [sacredbanana/AmigaGPT#3]
would it be possible for amigagpt to save the conversations so that the program can remember them in offline mode?

**Comment by vastago** [comment]
[](url)blob:https://web.telegram.org/d5f8c6a8-5a13-4e25-b1ed-f69cdb43376a

**Comment by sacredbanana** [comment]
That link gives me a 404

**Comment by vastago** [comment]
![alanUno](https://github.com/sacredbanana/AmigaGPT/assets/47063821/6da54811-9b44-4362-ab8e-2572810b7c42)

**Comment by vastago** [comment]
just for fun to create a small data base. Just a thought, a beer to your health!!! :)

**Comment by sacredbanana** [comment]
Thanks, I'll add offline mode to the list of features to add

**Comment by sacredbanana** [comment]
I've decided adding offline mode would be too much effort and it wouldn't get used much by people. My time right now is spent working on major features. If you really want to add messages to your conversation while offline you can always edit the `conversation-history.json` file located in the AmigaGPT directory.
