### ISSUE TITLE
AmigaGPT stops working after few questions

### ISSUE THREAD

**Issue by ales-zima** [sacredbanana/AmigaGPT#5]
Hi. I was trying your app in classic AmigaOS 3.2.2.1 with Roadshow TCP stack and AmiSSL 5.13 on real Amiga 1200 with TF1260 and after 2 or 5 questions AmigaGPT ends with "sending" and that's all. App is not responsive and start eating RAM until is fully exhausted. TCP stack and AmiSSL with IBrowse3 are working like a charm.

**Comment by polluks** [comment]
@ales-zima Did you run Enforcer?

**Comment by ales-zima** [comment]
Nope.

**Comment by sacredbanana** [comment]
I have fixed this in the 1.4.1 release. Please let me know if the issue is still present

**Comment by ales-zima** [comment]
Yes! It looks, that problem is fixed. Chat works now without problems. Thanks.
