### ISSUE TITLE
Use AmigaDOS $STACK: cookie for automatic stack allocation

### ISSUE THREAD

**Issue by bubbob42** [sacredbanana/AmigaGPT#9]
To prevent low stack when running from CLI, you may use the $STACK cookie, which is documented here:

https://github.com/thorfdbg/rkrm-dos/blob/main/dos.pdf

(Chapter 11.5.2)

Thanks for your great software!

**Comment by sacredbanana** [comment]
Thanks for letting me know about this and sharing this book! I'm excited to read it all. I have added the stack cookie in the latest 1.4.3 release!
